# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "cb272f200107709037772c0feae505bf"
application_url = "https://example.com"
embedded = true
name = "Conversion Copilot"

[access_scopes]
scopes = "read_products,write_products,write_files,read_locales,read_translations,write_translations"

[webhooks]
api_version = "2026-07"

  [[webhooks.subscriptions]]
  uri = "/webhooks/app/uninstalled"
  topics = [ "app/uninstalled" ]

  [[webhooks.subscriptions]]
  uri = "/webhooks/app/scopes_update"
  topics = [ "app/scopes_update" ]

  [[webhooks.subscriptions]]
  compliance_topics = [ "customers/data_request", "customers/redact", "shop/redact" ]
  uri = "/webhooks"

[auth]
redirect_urls = [ "https://example.com/api/auth" ]

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = true
